id: P006978
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016271
  title: རྩོད་ལན་བློ་དམན་སྙིང་གི་གདུང་སེལ་ག་བུར་ཐིག་པའི་སྤུན་ཟླ
  author: ''
  volumes:
    3d3f64c8adaf48db99d38d0ee231bf82:
      image_group_id: I00JW501150
      title: ''
      volume_number: 1
      total_pages: 114
ebook_metadata:
  title: རྩོད་ལན་བློ་དམན་སྙིང་གི་གདུང་སེལ་ག་བུར་ཐིག་པའི་སྤུན་ཟླ
  author: ''
  sku: P006978
  cover: cover.jpg
  layers:
  - pagination
